package orchestrator

import (
	"strings"
	"testing"

	"github.com/douglasjarquin/made/internal/daemon"
)

func TestRenderPipelineSummary_AllPassedNoFixes(t *testing.T) {
	stages := []daemon.StageResult{
		{Name: stageNameIntent, Result: stageResultPass},
		{Name: stageNameRebase, Result: stageResultPass},
		{Name: stageNameReview, Result: stageResultPass},
		{Name: stageNameTest, Result: stageResultPass},
		{Name: stageNameDocument, Result: stageResultPass},
		{Name: stageNameLint, Result: stageResultPass},
		{Name: stageNamePush, Result: stageResultPass},
	}
	messages := map[string]string{
		stageNameReview: "review passed: 0 auto-fix(es) applied, 0 finding(s) await human approval",
	}

	got := renderPipelineSummary(stages, messages, nil)

	if !strings.Contains(got, "Generated by [`made`](https://github.com/douglasjarquin/made)") {
		t.Fatalf("expected made attribution line, got:\n%s", got)
	}
	if !strings.Contains(got, "| Stage | Status | Notes |") {
		t.Fatalf("expected a status table header, got:\n%s", got)
	}
	if !strings.Contains(got, "| Intent | ✅ Passed | |") {
		t.Fatalf("expected a blank-notes Intent row, got:\n%s", got)
	}
	if !strings.Contains(got, "| Review | ✅ Passed | review passed: 0 auto-fix(es) applied, 0 finding(s) await human approval |") {
		t.Fatalf("expected the review row to carry its real message, got:\n%s", got)
	}
	if strings.Contains(got, "<details>") {
		t.Fatalf("expected no review-fixes details block when nothing was fixed, got:\n%s", got)
	}
}

func TestRenderPipelineSummary_FailedStageShowsMessage(t *testing.T) {
	stages := []daemon.StageResult{
		{Name: stageNameIntent, Result: stageResultPass},
		{Name: stageNameRebase, Result: stageResultFail},
	}
	messages := map[string]string{
		stageNameRebase: "rebase: conflict in file.go",
	}

	got := renderPipelineSummary(stages, messages, nil)

	if !strings.Contains(got, "| Rebase | ❌ Failed | rebase: conflict in file.go |") {
		t.Fatalf("expected the failed stage to show its message, got:\n%s", got)
	}
}

func TestRenderPipelineSummary_SkippedStageShowsMessage(t *testing.T) {
	stages := []daemon.StageResult{
		{Name: stageNameLint, Result: "skipped"},
	}
	messages := map[string]string{
		stageNameLint: "stage disabled",
	}

	got := renderPipelineSummary(stages, messages, nil)

	if !strings.Contains(got, "| Lint | ⏭️ Skipped | stage disabled |") {
		t.Fatalf("expected the skipped stage to show its message, got:\n%s", got)
	}
}

func TestRenderPipelineSummary_ReviewFixesDetailsBlock(t *testing.T) {
	stages := []daemon.StageResult{
		{Name: stageNameReview, Result: stageResultPass},
	}
	messages := map[string]string{
		stageNameReview: "review passed: 2 auto-fix(es) applied, 0 finding(s) await human approval",
	}
	fixes := []string{
		"Nested authorColors under gui as required by schema.",
		"Preserved unmanaged wildcard author colors.",
	}

	got := renderPipelineSummary(stages, messages, fixes)

	if !strings.Contains(got, "<summary><strong>Review fixes</strong></summary>") {
		t.Fatalf("expected a Review fixes details block, got:\n%s", got)
	}
	if !strings.Contains(got, "1. Nested authorColors under gui as required by schema.") {
		t.Fatalf("expected the first fix numbered, got:\n%s", got)
	}
	if !strings.Contains(got, "2. Preserved unmanaged wildcard author colors.") {
		t.Fatalf("expected the second fix numbered, got:\n%s", got)
	}
}

func TestRenderPipelineSummary_EmptyStagesReturnsEmpty(t *testing.T) {
	if got := renderPipelineSummary(nil, nil, nil); got != "" {
		t.Fatalf("expected empty summary for no stages, got:\n%s", got)
	}
}
