package orchestrator

import (
	"fmt"
	"strings"

	"github.com/douglasjarquin/made/internal/daemon"
)

const madeAttributionLine = "> Generated by [`made`](https://github.com/douglasjarquin/made)"

var pipelineSummaryStageDisplayName = map[string]string{
	stageNameIntent:   "Intent",
	stageNameRebase:   "Rebase",
	stageNameReview:   "Review",
	stageNameTest:     "Test",
	stageNameDocument: "Document",
	stageNameLint:     "Lint",
	stageNamePush:     "Push",
	stageNamePR:       "PR",
	stageNameCI:       "CI",
}

// renderPipelineSummary renders the human-readable body of the PR's "##
// Pipeline" section: a made-branded status table plus, when the review
// stage auto-fixed anything, a collapsible list of what it fixed. It
// renders only the finished stages it is given - by construction that
// excludes PR and CI, since neither has run yet when this is called.
func renderPipelineSummary(stages []daemon.StageResult, messages map[string]string, reviewFixDescriptions []string) string {
	if len(stages) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(madeAttributionLine)
	b.WriteString("\n\n")
	b.WriteString("| Stage | Status | Notes |\n")
	b.WriteString("|---|:---:|---|\n")
	for _, stage := range stages {
		name := pipelineSummaryStageDisplayName[stage.Name]
		if name == "" {
			name = stage.Name
		}
		notes := pipelineSummaryNotes(stage, messages[stage.Name])
		if notes == "" {
			fmt.Fprintf(&b, "| %s | %s | |\n", name, pipelineSummaryStatus(stage.Result))
		} else {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", name, pipelineSummaryStatus(stage.Result), notes)
		}
	}

	if len(reviewFixDescriptions) > 0 {
		b.WriteString("\n<details>\n<summary><strong>Review fixes</strong></summary>\n\n")
		for i, fix := range reviewFixDescriptions {
			fmt.Fprintf(&b, "%d. %s\n", i+1, fix)
		}
		b.WriteString("\n</details>\n")
	}

	return strings.TrimRight(b.String(), "\n")
}

func pipelineSummaryStatus(result string) string {
	switch result {
	case stageResultPass:
		return "✅ Passed"
	case stageResultFail:
		return "❌ Failed"
	case "skipped":
		return "⏭️ Skipped"
	default:
		return result
	}
}

// pipelineSummaryNotes leaves a passing, non-Review stage's Notes cell
// blank: its status column already says "Passed", and the underlying
// message is generic ("push succeeded") rather than informative. A failure,
// a skip, or the Review stage - whose message carries the real auto-fix and
// pending-finding counts - always surfaces its message instead.
func pipelineSummaryNotes(stage daemon.StageResult, message string) string {
	if stage.Result != stageResultPass || stage.Name == stageNameReview {
		return message
	}
	return ""
}
