// Package cursor generates and maintains project-local Cursor projections
// (.cursor/agents/made-reviewer.md, .cursor/skills/verify-with-made/SKILL.md)
// so a Cursor Cloud coding agent can complete made verify's exact-SHA
// verification (project issue #41) without Made launching a daemon, gate, or
// its own review harness. See project issue #42.
package cursor

import (
	"bytes"
	"fmt"

	"github.com/douglasjarquin/made/internal/config"
)

const (
	ReviewerRelPath = ".cursor/agents/made-reviewer.md"
	SkillRelPath    = ".cursor/skills/verify-with-made/SKILL.md"

	GeneratedMarker = "Generated by Made from project config; run `made cursor sync`."
)

// ManagedFile is one Cursor projection Made owns. Content is nil when the
// current configuration says the file should not exist (e.g. no reviewer
// while review.executors.cursor.model is unset).
type ManagedFile struct {
	RelPath string
	Content []byte
}

// ManagedFiles derives the exact set of Cursor projections trusted config
// implies, in a fixed order, so callers never depend on map iteration order.
func ManagedFiles(cfg config.Config) ([]ManagedFile, error) {
	files := []ManagedFile{
		{RelPath: SkillRelPath, Content: []byte(SkillMarkdown())},
	}

	model := cfg.Review.Executors.Cursor.Model
	if model == "" {
		files = append(files, ManagedFile{RelPath: ReviewerRelPath, Content: nil})
		return files, nil
	}
	reviewer, err := ReviewerMarkdown(model, cfg.Review.Guides)
	if err != nil {
		return nil, fmt.Errorf("cursor: render reviewer: %w", err)
	}
	files = append(files, ManagedFile{RelPath: ReviewerRelPath, Content: []byte(reviewer)})
	return files, nil
}

func hasMarker(data []byte) bool {
	return bytes.Contains(data, []byte(GeneratedMarker))
}
